name: Build Replicate Layer ARM64
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Create replicate layer for ARM64
        run: |
          mkdir python
          
          # Install for ARM64 architecture specifically
          pip install replicate \
            --platform linux_aarch64 \
            --implementation cp \
            --python-version 3.13 \
            --only-binary=:all: \
            --target python/ \
            --no-cache-dir
          
          # Verify structure
          echo "=== Layer contents ==="
          ls -la python/
          
          # Create zip
          zip -r replicate-layer-py313-arm64.zip python/
          
          # Show zip info
          echo "=== Zip file info ==="
          unzip -l replicate-layer-py313-arm64.zip | head -20
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: replicate-layer-py313-arm64
          path: replicate-layer-py313-arm64.zip
