name: Build Pillow Layer ARM64
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Create pillow layer for ARM64
        run: |
          # Create layer structure
          mkdir python
          
          # Install Pillow for ARM64 architecture specifically
          pip install pillow \
            --platform linux_aarch64 \
            --implementation cp \
            --python-version 3.13 \
            --only-binary=:all: \
            --target python/ \
            --no-cache-dir
          
          # Verify contents
          echo "=== Layer directory contents ==="
          ls -la python/
          echo "=== Pillow directory contents ==="
          ls python/PIL/ | head -10
          
          # Create zip with correct structure
          zip -r pillow-layer.zip python/
          
          # Verify zip structure
          echo "=== Zip contents ==="
          unzip -l pillow-layer.zip | head -10
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pillow-layer-py313-arm64
          path: pillow-layer.zip
