name: Build Pillow Layer Python 3.12
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Create pillow layer
        run: |
          mkdir python
          pip install --upgrade pip
          pip install pillow -t python/
          
          echo "=== PIL directory contents ==="
          ls python/PIL/ | head -10
          
          echo "=== Looking for _imaging files ==="
          find python/ -name "*imaging*" -type f
          
          echo "=== Testing PIL import ==="
          cd python && python -c "from PIL import Image, ImageOps; print('PIL imported successfully')" && cd ..
          
          zip -r pillow-layer-py312.zip python/
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pillow-layer-py312
          path: pillow-layer-py312.zip
