name: Build Replicate Layer ARM64
on: 
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Create replicate layer
        run: |
          mkdir python
          pip install replicate -t python/
          zip -r replicate-layer-py313-arm64.zip python/
          ls -la replicate-layer-py313-arm64.zip
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: replicate-layer-py313-arm64
          path: replicate-layer-py313-arm64.zip
